blueprint: site

title:
  de: Seite
  en: Site

tabs:
  pages:
    label: Pages
    icon: page
    columns:
      - width: 2/3
        sections:
          pages:
            label: Pages
            type: pages
            info: '/{{ page.slug }}'
            create:
              - home
              - page
            templates:
              - home
              - page
              - error
            image: icon
  # navigation: tabs/navigation
  # seo: seo/site
